name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Backend
      - name: Build Backend Image
        run: docker build -t ahte786/carbon-backend ./server

      - name: Push Backend Image
        run: docker push ahte786/carbon-backend

      # Build Frontend
      - name: Build Frontend Image
        run: docker build -t ahte786/carbon-frontend ./client

      - name: Push Frontend Image
        run: docker push ahte786/carbon-frontend